// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from '@hey-api/client-fetch';
import type {
  GetPingError,
  GetPingResponse,
  GetWeaponsForActivityData,
  GetWeaponsForActivityError,
  GetWeaponsForActivityResponse,
} from './types.gen';

export const client = createClient(createConfig());

export const getPing = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPingResponse,
    GetPingError,
    ThrowOnError
  >({
    ...options,
    url: '/ping',
  });
};

export const getWeaponsForActivity = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetWeaponsForActivityData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetWeaponsForActivityResponse,
    GetWeaponsForActivityError,
    ThrowOnError
  >({
    ...options,
    url: '/activities/{activityId}/weapons',
  });
};
