// This file is auto-generated by @hey-api/openapi-ts
import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import {
  completeSessionResponseTransformer,
  createSnapshotResponseTransformer,
  getActivitiesResponseTransformer,
  getActivityResponseTransformer,
  getBestPerformingLoadoutsResponseTransformer,
  getFireteamResponseTransformer,
  getSessionAggregatesResponseTransformer,
  getSessionResponseTransformer,
  getSessionsResponseTransformer,
  getSnapshotAggregatesResponseTransformer,
  getSnapshotResponseTransformer,
  getSnapshotsResponseTransformer,
  getUserResponseTransformer,
  getUserSessionsResponseTransformer,
  loginResponseTransformer,
  refreshTokenResponseTransformer,
  startSessionResponseTransformer,
  startUserSessionResponseTransformer,
  updateSessionResponseTransformer,
  updateSnapshotResponseTransformer,
} from './transformers.gen';
import type {
  BackfillAggregateDataData,
  BackfillAggregateDataResponses,
  BackfillAllUsersCharacterIdsData,
  BackfillAllUsersCharacterIdsResponses,
  BackfillSnapshotInfoData,
  BackfillSnapshotInfoResponses,
  CompleteSessionData,
  CompleteSessionResponses,
  CreateSnapshotData,
  CreateSnapshotResponses,
  GetActivitiesData,
  GetActivitiesResponses,
  GetActivityData,
  GetActivityErrors,
  GetActivityResponses,
  GetBestPerformingLoadoutsData,
  GetBestPerformingLoadoutsResponses,
  GetFireteamData,
  GetFireteamErrors,
  GetFireteamResponses,
  GetPingData,
  GetPingResponses,
  GetSessionAggregatesData,
  GetSessionAggregatesResponses,
  GetSessionData,
  GetSessionResponses,
  GetSessionsData,
  GetSessionsResponses,
  GetSnapshotAggregatesData,
  GetSnapshotAggregatesResponses,
  GetSnapshotData,
  GetSnapshotResponses,
  GetSnapshotsData,
  GetSnapshotsResponses,
  GetUserData,
  GetUserErrors,
  GetUserResponses,
  GetUserSessionsData,
  GetUserSessionsResponses,
  LoginData,
  LoginResponses,
  MergeSnapshotsData,
  MergeSnapshotsErrors,
  MergeSnapshotsResponses,
  RefreshTokenData,
  RefreshTokenResponses,
  SearchData,
  SearchResponses,
  StartSessionData,
  StartSessionErrors,
  StartSessionResponses,
  StartUserSessionData,
  StartUserSessionErrors,
  StartUserSessionResponses,
  UpdateSessionData,
  UpdateSessionResponses,
  UpdateSnapshotData,
  UpdateSnapshotErrors,
  UpdateSnapshotResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

export const getPing = <ThrowOnError extends boolean = false>(
  options?: Options<GetPingData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetPingResponses, unknown, ThrowOnError>({
    url: '/ping',
    ...options,
  });

export const backfillAllUsersCharacterIds = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<BackfillAllUsersCharacterIdsData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    BackfillAllUsersCharacterIdsResponses,
    unknown,
    ThrowOnError
  >({ url: '/admin/backfill-character-ids', ...options });

export const backfillSnapshotInfo = <ThrowOnError extends boolean = false>(
  options?: Options<BackfillSnapshotInfoData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    BackfillSnapshotInfoResponses,
    unknown,
    ThrowOnError
  >({ url: '/admin/backfill-snapshot-base-info', ...options });

export const backfillAggregateData = <ThrowOnError extends boolean = false>(
  options?: Options<BackfillAggregateDataData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    BackfillAggregateDataResponses,
    unknown,
    ThrowOnError
  >({ url: '/admin/backfill-aggregate-data', ...options });

/**
 * return a list from bungie of matching users
 */
export const search = <ThrowOnError extends boolean = false>(
  options?: Options<SearchData, ThrowOnError>,
) =>
  (options?.client ?? client).post<SearchResponses, unknown, ThrowOnError>({
    url: '/search',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

export const getFireteam = <ThrowOnError extends boolean = false>(
  options: Options<GetFireteamData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetFireteamResponses,
    GetFireteamErrors,
    ThrowOnError
  >({
    responseTransformer: getFireteamResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/fireteam',
    ...options,
  });

export const getUser = <ThrowOnError extends boolean = false>(
  options: Options<GetUserData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetUserResponses, GetUserErrors, ThrowOnError>(
    {
      responseTransformer: getUserResponseTransformer,
      url: '/users/{userId}',
      ...options,
    },
  );

export const login = <ThrowOnError extends boolean = false>(
  options?: Options<LoginData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LoginResponses, unknown, ThrowOnError>({
    responseTransformer: loginResponseTransformer,
    url: '/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

export const refreshToken = <ThrowOnError extends boolean = false>(
  options?: Options<RefreshTokenData, ThrowOnError>,
) =>
  (options?.client ?? client).post<
    RefreshTokenResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: refreshTokenResponseTransformer,
    url: '/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  });

export const getUserSessions = <ThrowOnError extends boolean = false>(
  options: Options<GetUserSessionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetUserSessionsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getUserSessionsResponseTransformer,
    url: '/users/{userId}/sessions',
    ...options,
  });

/**
 * Create a new session
 */
export const startUserSession = <ThrowOnError extends boolean = false>(
  options: Options<StartUserSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartUserSessionResponses,
    StartUserSessionErrors,
    ThrowOnError
  >({
    responseTransformer: startUserSessionResponseTransformer,
    url: '/users/{userId}/sessions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Returns a list of snapshots in the system for a character
 */
export const getSnapshots = <ThrowOnError extends boolean = false>(
  options: Options<GetSnapshotsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSnapshotsResponses, unknown, ThrowOnError>({
    responseTransformer: getSnapshotsResponseTransformer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/snapshots',
    ...options,
  });

/**
 * Creates a new snapshot in the system and returns a list of
 */
export const createSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<CreateSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    CreateSnapshotResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: createSnapshotResponseTransformer,
    url: '/snapshots',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Returns a snapshot in the system for a character
 */
export const getSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<GetSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSnapshotResponses, unknown, ThrowOnError>({
    responseTransformer: getSnapshotResponseTransformer,
    url: '/snapshots/{snapshotId}',
    ...options,
  });

/**
 * Updates a snapshot in the system
 */
export const updateSnapshot = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSnapshotData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    UpdateSnapshotResponses,
    UpdateSnapshotErrors,
    ThrowOnError
  >({
    responseTransformer: updateSnapshotResponseTransformer,
    url: '/snapshots/{snapshotId}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Merge two snapshots into a single snapshot
 */
export const mergeSnapshots = <ThrowOnError extends boolean = false>(
  options: Options<MergeSnapshotsData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    MergeSnapshotsResponses,
    MergeSnapshotsErrors,
    ThrowOnError
  >({
    url: '/snapshots/{snapshotId}/merge',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Returns a collection of aggregate metrics for a snapshot
 */
export const getSnapshotAggregates = <ThrowOnError extends boolean = false>(
  options: Options<GetSnapshotAggregatesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSnapshotAggregatesResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getSnapshotAggregatesResponseTransformer,
    url: '/snapshots/{snapshotId}/aggregates',
    ...options,
  });

export const getActivities = <ThrowOnError extends boolean = false>(
  options: Options<GetActivitiesData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetActivitiesResponses, unknown, ThrowOnError>(
    {
      responseTransformer: getActivitiesResponseTransformer,
      url: '/activities',
      ...options,
    },
  );

export const getActivity = <ThrowOnError extends boolean = false>(
  options: Options<GetActivityData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetActivityResponses,
    GetActivityErrors,
    ThrowOnError
  >({
    responseTransformer: getActivityResponseTransformer,
    url: '/activities/{activityId}',
    ...options,
  });

export const getSessions = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionsData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSessionsResponses, unknown, ThrowOnError>({
    responseTransformer: getSessionsResponseTransformer,
    url: '/sessions',
    ...options,
  });

/**
 * Create a new session
 */
export const startSession = <ThrowOnError extends boolean = false>(
  options: Options<StartSessionData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    StartSessionResponses,
    StartSessionErrors,
    ThrowOnError
  >({
    responseTransformer: startSessionResponseTransformer,
    url: '/sessions',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get a specific session
 */
export const getSession = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionData, ThrowOnError>,
) =>
  (options.client ?? client).get<GetSessionResponses, unknown, ThrowOnError>({
    responseTransformer: getSessionResponseTransformer,
    url: '/sessions/{sessionId}',
    ...options,
  });

/**
 * Update a session
 */
export const updateSession = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSessionData, ThrowOnError>,
) =>
  (options.client ?? client).put<UpdateSessionResponses, unknown, ThrowOnError>(
    {
      responseTransformer: updateSessionResponseTransformer,
      url: '/sessions/{sessionId}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    },
  );

/**
 * Complete a session
 */
export const completeSession = <ThrowOnError extends boolean = false>(
  options: Options<CompleteSessionData, ThrowOnError>,
) =>
  (options.client ?? client).put<
    CompleteSessionResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: completeSessionResponseTransformer,
    url: '/sessions/{sessionId}/complete',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const getSessionAggregates = <ThrowOnError extends boolean = false>(
  options: Options<GetSessionAggregatesData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetSessionAggregatesResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getSessionAggregatesResponseTransformer,
    url: '/sessions/{sessionId}/aggregates',
    ...options,
  });

export const getBestPerformingLoadouts = <ThrowOnError extends boolean = false>(
  options: Options<GetBestPerformingLoadoutsData, ThrowOnError>,
) =>
  (options.client ?? client).get<
    GetBestPerformingLoadoutsResponses,
    unknown,
    ThrowOnError
  >({
    responseTransformer: getBestPerformingLoadoutsResponseTransformer,
    url: '/metrics/best-performing-loadouts',
    ...options,
  });
