// This file is auto-generated by @hey-api/openapi-ts

import type { GetSnapshotsResponse, CreateSnapshotResponse } from './types.gen';

const itemSnapshotSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

const characterSnapshotSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  data.items = data.items.map((item: any) => {
    return itemSnapshotSchemaResponseTransformer(item);
  });
  return data;
};

export const getSnapshotsResponseTransformer = async (
  data: any,
): Promise<GetSnapshotsResponse> => {
  data = data.map((item: any) => {
    return characterSnapshotSchemaResponseTransformer(item);
  });
  return data;
};

export const createSnapshotResponseTransformer = async (
  data: any,
): Promise<CreateSnapshotResponse> => {
  data = characterSnapshotSchemaResponseTransformer(data);
  return data;
};
