// This file is auto-generated by @hey-api/openapi-ts
import type {
  CreateSnapshotResponse,
  GetSnapshotResponse,
  GetSnapshotsResponse,
  LoginResponse,
  RefreshTokenResponse,
} from './types.gen';

const authResponseSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

export const loginResponseTransformer = async (
  data: any,
): Promise<LoginResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};

export const refreshTokenResponseTransformer = async (
  data: any,
): Promise<RefreshTokenResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};

const itemSnapshotSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

const characterSnapshotSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  data.items = data.items.map((item: any) => {
    return itemSnapshotSchemaResponseTransformer(item);
  });
  return data;
};

export const getSnapshotsResponseTransformer = async (
  data: any,
): Promise<GetSnapshotsResponse> => {
  data = data.map((item: any) => {
    return characterSnapshotSchemaResponseTransformer(item);
  });
  return data;
};

export const createSnapshotResponseTransformer = async (
  data: any,
): Promise<CreateSnapshotResponse> => {
  data = characterSnapshotSchemaResponseTransformer(data);
  return data;
};

export const getSnapshotResponseTransformer = async (
  data: any,
): Promise<GetSnapshotResponse> => {
  data = characterSnapshotSchemaResponseTransformer(data);
  return data;
};
