// This file is auto-generated by @hey-api/openapi-ts
import type {
  CompleteSessionResponse,
  CreateSnapshotResponse,
  GetActivitiesResponse,
  GetActivityResponse,
  GetBestPerformingLoadoutsResponse,
  GetFireteamResponse,
  GetSessionAggregatesResponse,
  GetSessionResponse,
  GetSessionsResponse,
  GetSnapshotAggregatesResponse,
  GetSnapshotResponse,
  GetSnapshotsResponse,
  GetUserResponse,
  GetUserSessionsResponse,
  LoginResponse,
  RefreshTokenResponse,
  StartSessionResponse,
  StartUserSessionResponse,
  UpdateSessionResponse,
  UpdateSnapshotResponse,
} from './types.gen';

const characterSchemaResponseTransformer = (data: any) => {
  data.light = BigInt(data.light.toString());
  return data;
};

const fireteamMemberSchemaResponseTransformer = (data: any) => {
  data.characters = data.characters.map((item: any) =>
    characterSchemaResponseTransformer(item),
  );
  return data;
};

export const getFireteamResponseTransformer = async (
  data: any,
): Promise<GetFireteamResponse> => {
  data = data.map((item: any) => fireteamMemberSchemaResponseTransformer(item));
  return data;
};

const profileSchemaResponseTransformer = (data: any) => {
  data.characters = data.characters.map((item: any) =>
    characterSchemaResponseTransformer(item),
  );
  return data;
};

export const getUserResponseTransformer = async (
  data: any,
): Promise<GetUserResponse> => {
  data = profileSchemaResponseTransformer(data);
  return data;
};

const authResponseSchemaResponseTransformer = (data: any) => {
  data.timestamp = new Date(data.timestamp);
  return data;
};

export const loginResponseTransformer = async (
  data: any,
): Promise<LoginResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};

export const refreshTokenResponseTransformer = async (
  data: any,
): Promise<RefreshTokenResponse> => {
  data = authResponseSchemaResponseTransformer(data);
  return data;
};

const sessionSchemaResponseTransformer = (data: any) => {
  data.startedAt = new Date(data.startedAt);
  if (data.completedAt) {
    data.completedAt = new Date(data.completedAt);
  }
  return data;
};

export const getUserSessionsResponseTransformer = async (
  data: any,
): Promise<GetUserSessionsResponse> => {
  data = data.map((item: any) => sessionSchemaResponseTransformer(item));
  return data;
};

export const startUserSessionResponseTransformer = async (
  data: any,
): Promise<StartUserSessionResponse> => {
  data = sessionSchemaResponseTransformer(data);
  return data;
};

const characterSnapshotSchemaResponseTransformer = (data: any) => {
  data.createdAt = new Date(data.createdAt);
  data.updatedAt = new Date(data.updatedAt);
  return data;
};

export const getSnapshotsResponseTransformer = async (
  data: any,
): Promise<GetSnapshotsResponse> => {
  data = data.map((item: any) =>
    characterSnapshotSchemaResponseTransformer(item),
  );
  return data;
};

export const createSnapshotResponseTransformer = async (
  data: any,
): Promise<CreateSnapshotResponse> => {
  data = characterSnapshotSchemaResponseTransformer(data);
  return data;
};

export const getSnapshotResponseTransformer = async (
  data: any,
): Promise<GetSnapshotResponse> => {
  data = characterSnapshotSchemaResponseTransformer(data);
  return data;
};

export const updateSnapshotResponseTransformer = async (
  data: any,
): Promise<UpdateSnapshotResponse> => {
  data = characterSnapshotSchemaResponseTransformer(data);
  return data;
};

const activityHistorySchemaResponseTransformer = (data: any) => {
  data.period = new Date(data.period);
  data.referenceId = BigInt(data.referenceId.toString());
  data.activityHash = BigInt(data.activityHash.toString());
  return data;
};

const aggregateSchemaResponseTransformer = (data: any) => {
  data.activityDetails = activityHistorySchemaResponseTransformer(
    data.activityDetails,
  );
  data.createdAt = new Date(data.createdAt);
  return data;
};

export const getSnapshotAggregatesResponseTransformer = async (
  data: any,
): Promise<GetSnapshotAggregatesResponse> => {
  data = data.map((item: any) => aggregateSchemaResponseTransformer(item));
  return data;
};

const detailActivitySchemaResponseTransformer = (data: any) => {
  data.activity = activityHistorySchemaResponseTransformer(data.activity);
  if (data.aggregate) {
    data.aggregate = aggregateSchemaResponseTransformer(data.aggregate);
  }
  return data;
};

export const getActivitiesResponseTransformer = async (
  data: any,
): Promise<GetActivitiesResponse> => {
  data = data.map((item: any) => detailActivitySchemaResponseTransformer(item));
  return data;
};

export const getActivityResponseTransformer = async (
  data: any,
): Promise<GetActivityResponse> => {
  data.activity = activityHistorySchemaResponseTransformer(data.activity);
  if (data.aggregate) {
    data.aggregate = aggregateSchemaResponseTransformer(data.aggregate);
  }
  return data;
};

export const getSessionsResponseTransformer = async (
  data: any,
): Promise<GetSessionsResponse> => {
  data = data.map((item: any) => sessionSchemaResponseTransformer(item));
  return data;
};

export const startSessionResponseTransformer = async (
  data: any,
): Promise<StartSessionResponse> => {
  data = sessionSchemaResponseTransformer(data);
  return data;
};

export const getSessionResponseTransformer = async (
  data: any,
): Promise<GetSessionResponse> => {
  data = sessionSchemaResponseTransformer(data);
  return data;
};

export const updateSessionResponseTransformer = async (
  data: any,
): Promise<UpdateSessionResponse> => {
  data = sessionSchemaResponseTransformer(data);
  return data;
};

export const completeSessionResponseTransformer = async (
  data: any,
): Promise<CompleteSessionResponse> => {
  data = sessionSchemaResponseTransformer(data);
  return data;
};

export const getSessionAggregatesResponseTransformer = async (
  data: any,
): Promise<GetSessionAggregatesResponse> => {
  data.aggregates = data.aggregates.map((item: any) =>
    aggregateSchemaResponseTransformer(item),
  );
  return data;
};

export const getBestPerformingLoadoutsResponseTransformer = async (
  data: any,
): Promise<GetBestPerformingLoadoutsResponse> => {
  data.items = data.items.map((item: any) =>
    characterSnapshotSchemaResponseTransformer(item),
  );
  return data;
};
