// This file is auto-generated by @hey-api/openapi-ts

import {
  createClient,
  createConfig,
  type OptionsLegacyParser,
} from '@hey-api/client-fetch';
import type {
  GetPingError,
  GetPingResponse,
  GetActivitiesData,
  GetActivitiesError,
  GetActivitiesResponse,
  GetActivityData,
  GetActivityError,
  GetActivityResponse,
} from './types.gen';

export const client = createClient(createConfig());

export const getPing = <ThrowOnError extends boolean = false>(
  options?: OptionsLegacyParser<unknown, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetPingResponse,
    GetPingError,
    ThrowOnError
  >({
    ...options,
    url: '/ping',
  });
};

export const getActivities = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetActivitiesData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetActivitiesResponse,
    GetActivitiesError,
    ThrowOnError
  >({
    ...options,
    url: '/activities',
  });
};

export const getActivity = <ThrowOnError extends boolean = false>(
  options: OptionsLegacyParser<GetActivityData, ThrowOnError>,
) => {
  return (options?.client ?? client).get<
    GetActivityResponse,
    GetActivityError,
    ThrowOnError
  >({
    ...options,
    url: '/activities/{activityId}',
  });
};
